// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYq_oSZEDDGt4PqrivQWb5AG7JY9RODWc',
    appId: '1:871370921599:android:4a619a1b42252056d1914a',
    messagingSenderId: '871370921599',
    projectId: 'biblioteca-online-flutter',
    databaseURL: 'https://biblioteca-online-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biblioteca-online-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZcrNjcchw56aAInwbzSSvPv_m0nMIZew',
    appId: '1:871370921599:ios:001a805692d7f7f2d1914a',
    messagingSenderId: '871370921599',
    projectId: 'biblioteca-online-flutter',
    databaseURL: 'https://biblioteca-online-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biblioteca-online-flutter.appspot.com',
    androidClientId: '871370921599-c6g90vcs3jrqd0aad6jtr79nrv1vv2hd.apps.googleusercontent.com',
    iosClientId: '871370921599-pfqliirrjgf7odao1e4g82la083fll7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibliotecaDigitalProyectoCftic',
  );
}
